// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AbrirBaseDatos(arg1:string):Promise<void>;

export function CerrarBaseDatos():Promise<void>;

export function DescargarBD(arg1:string):Promise<void>;

export function EliminarExpediente(arg1:number):Promise<void>;

export function GetBackupMaxCopies():Promise<number>;

export function GuardarExpediente(arg1:Record<string, any>):Promise<number>;

export function GuardarNuevoCatalogo(arg1:string,arg2:string,arg3:Record<string, any>):Promise<number>;

export function ObtenerCatalogos():Promise<Record<string, Array<main.CatalogoItem>>>;

export function ObtenerDocumentosPendientes():Promise<Array<main.Row>>;

export function ObtenerExpedientePorId(arg1:number):Promise<main.Row>;

export function ObtenerExpedientes(arg1:string):Promise<Array<main.Row>>;

export function ObtenerHistorialCompleto(arg1:number):Promise<Array<main.Row>>;

export function ObtenerRutaProcesos():Promise<Array<main.Row>>;

export function OptimizarBD():Promise<void>;

export function SetBackupMaxCopies(arg1:number):Promise<void>;
