// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbrirBaseDatos(arg1) {
  return window['go']['main']['App']['AbrirBaseDatos'](arg1);
}

export function AbrirDialogoBD() {
  return window['go']['main']['App']['AbrirDialogoBD']();
}

export function AgregarRutaProceso(arg1, arg2) {
  return window['go']['main']['App']['AgregarRutaProceso'](arg1, arg2);
}

export function CerrarBaseDatos() {
  return window['go']['main']['App']['CerrarBaseDatos']();
}

export function DescargarBD(arg1) {
  return window['go']['main']['App']['DescargarBD'](arg1);
}

export function EliminarFila(arg1, arg2) {
  return window['go']['main']['App']['EliminarFila'](arg1, arg2);
}

export function EliminarRutaProceso(arg1) {
  return window['go']['main']['App']['EliminarRutaProceso'](arg1);
}

export function GetBackupMaxCopies() {
  return window['go']['main']['App']['GetBackupMaxCopies']();
}

export function GuardarDialogoBD(arg1) {
  return window['go']['main']['App']['GuardarDialogoBD'](arg1);
}

export function GuardarFila(arg1, arg2) {
  return window['go']['main']['App']['GuardarFila'](arg1, arg2);
}

export function GuardarNuevoCatalogo(arg1, arg2, arg3) {
  return window['go']['main']['App']['GuardarNuevoCatalogo'](arg1, arg2, arg3);
}

export function ObtenerCatalogos() {
  return window['go']['main']['App']['ObtenerCatalogos']();
}

export function ObtenerColumnasVista(arg1) {
  return window['go']['main']['App']['ObtenerColumnasVista'](arg1);
}

export function ObtenerDocumentosPendientes() {
  return window['go']['main']['App']['ObtenerDocumentosPendientes']();
}

export function ObtenerExpedientesDisponiblesRuta() {
  return window['go']['main']['App']['ObtenerExpedientesDisponiblesRuta']();
}

export function ObtenerFilaPorId(arg1, arg2) {
  return window['go']['main']['App']['ObtenerFilaPorId'](arg1, arg2);
}

export function ObtenerFilas(arg1, arg2) {
  return window['go']['main']['App']['ObtenerFilas'](arg1, arg2);
}

export function ObtenerHistorialFila(arg1, arg2) {
  return window['go']['main']['App']['ObtenerHistorialFila'](arg1, arg2);
}

export function ObtenerRutaProcesos() {
  return window['go']['main']['App']['ObtenerRutaProcesos']();
}

export function ObtenerRutaProcesosData() {
  return window['go']['main']['App']['ObtenerRutaProcesosData']();
}

export function OptimizarBD() {
  return window['go']['main']['App']['OptimizarBD']();
}

export function SetBackupMaxCopies(arg1) {
  return window['go']['main']['App']['SetBackupMaxCopies'](arg1);
}

export function ToggleRutaProceso(arg1, arg2) {
  return window['go']['main']['App']['ToggleRutaProceso'](arg1, arg2);
}
