// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AbrirBaseDatos(arg1:string):Promise<void>;

export function AbrirDialogoBD():Promise<string>;

export function AgregarRutaProceso(arg1:string,arg2:number):Promise<number>;

export function CerrarBaseDatos():Promise<void>;

export function DescargarBD(arg1:string):Promise<void>;

export function EliminarFila(arg1:string,arg2:number):Promise<void>;

export function EliminarRutaProceso(arg1:number):Promise<void>;

export function GetBackupMaxCopies():Promise<number>;

export function GuardarDialogoBD(arg1:string):Promise<string>;

export function GuardarFila(arg1:string,arg2:Record<string, any>):Promise<number>;

export function GuardarNuevoCatalogo(arg1:string,arg2:string,arg3:Record<string, any>):Promise<number>;

export function ObtenerCatalogos():Promise<Record<string, Array<main.CatalogoItem>>>;

export function ObtenerColumnasVista(arg1:string):Promise<Array<string>>;

export function ObtenerDocumentosPendientes():Promise<Array<main.Row>>;

export function ObtenerFilaPorId(arg1:string,arg2:number):Promise<main.Row>;

export function ObtenerFilas(arg1:string,arg2:string):Promise<Array<main.Row>>;

export function ObtenerHistorialFila(arg1:string,arg2:number):Promise<Array<main.Row>>;

export function ObtenerRutaProcesos():Promise<Array<main.Row>>;

export function ObtenerRutaProcesosData():Promise<main.RutaProcesosGanttData>;

export function OptimizarBD():Promise<void>;

export function SetBackupMaxCopies(arg1:number):Promise<void>;

export function ToggleRutaProceso(arg1:number,arg2:boolean):Promise<void>;
