// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbrirBaseDatos(arg1) {
  return window['go']['main']['App']['AbrirBaseDatos'](arg1);
}

export function AbrirDialogoBD() {
  return window['go']['main']['App']['AbrirDialogoBD']();
}

export function ActualizarRutaProcesosJunta(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ActualizarRutaProcesosJunta'](arg1, arg2, arg3, arg4);
}

export function ActualizarRutaProcesosLeyenda(arg1, arg2, arg3) {
  return window['go']['main']['App']['ActualizarRutaProcesosLeyenda'](arg1, arg2, arg3);
}

export function AgregarRutaProcesosProceso(arg1, arg2, arg3) {
  return window['go']['main']['App']['AgregarRutaProcesosProceso'](arg1, arg2, arg3);
}

export function AgregarRutaProcesosSemana(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AgregarRutaProcesosSemana'](arg1, arg2, arg3, arg4);
}

export function CerrarBaseDatos() {
  return window['go']['main']['App']['CerrarBaseDatos']();
}

export function CrearRutaProcesosHoja(arg1) {
  return window['go']['main']['App']['CrearRutaProcesosHoja'](arg1);
}

export function CrearRutaProcesosJunta(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CrearRutaProcesosJunta'](arg1, arg2, arg3, arg4);
}

export function CrearRutaProcesosLeyenda(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CrearRutaProcesosLeyenda'](arg1, arg2, arg3, arg4, arg5);
}

export function DescargarBD(arg1) {
  return window['go']['main']['App']['DescargarBD'](arg1);
}

export function EliminarCronogramaDia(arg1) {
  return window['go']['main']['App']['EliminarCronogramaDia'](arg1);
}

export function EliminarFila(arg1, arg2) {
  return window['go']['main']['App']['EliminarFila'](arg1, arg2);
}

export function EliminarRutaProcesosHoja(arg1) {
  return window['go']['main']['App']['EliminarRutaProcesosHoja'](arg1);
}

export function EliminarRutaProcesosJunta(arg1) {
  return window['go']['main']['App']['EliminarRutaProcesosJunta'](arg1);
}

export function EliminarRutaProcesosLeyenda(arg1) {
  return window['go']['main']['App']['EliminarRutaProcesosLeyenda'](arg1);
}

export function EliminarRutaProcesosProceso(arg1) {
  return window['go']['main']['App']['EliminarRutaProcesosProceso'](arg1);
}

export function EliminarRutaProcesosSemanas(arg1, arg2) {
  return window['go']['main']['App']['EliminarRutaProcesosSemanas'](arg1, arg2);
}

export function GetBackupMaxCopies() {
  return window['go']['main']['App']['GetBackupMaxCopies']();
}

export function GuardarCronogramaDia(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GuardarCronogramaDia'](arg1, arg2, arg3, arg4);
}

export function GuardarDialogoBD(arg1) {
  return window['go']['main']['App']['GuardarDialogoBD'](arg1);
}

export function GuardarFila(arg1, arg2) {
  return window['go']['main']['App']['GuardarFila'](arg1, arg2);
}

export function GuardarNuevoCatalogo(arg1, arg2, arg3) {
  return window['go']['main']['App']['GuardarNuevoCatalogo'](arg1, arg2, arg3);
}

export function ObtenerCatalogos() {
  return window['go']['main']['App']['ObtenerCatalogos']();
}

export function ObtenerColumnasVista(arg1) {
  return window['go']['main']['App']['ObtenerColumnasVista'](arg1);
}

export function ObtenerDocumentosPendientes() {
  return window['go']['main']['App']['ObtenerDocumentosPendientes']();
}

export function ObtenerFilaPorId(arg1, arg2) {
  return window['go']['main']['App']['ObtenerFilaPorId'](arg1, arg2);
}

export function ObtenerFilas(arg1, arg2) {
  return window['go']['main']['App']['ObtenerFilas'](arg1, arg2);
}

export function ObtenerFilasPaginado(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ObtenerFilasPaginado'](arg1, arg2, arg3, arg4);
}

export function ObtenerHistorialFila(arg1, arg2) {
  return window['go']['main']['App']['ObtenerHistorialFila'](arg1, arg2);
}

export function ObtenerRutaProcesos() {
  return window['go']['main']['App']['ObtenerRutaProcesos']();
}

export function ObtenerRutaProcesosData(arg1, arg2) {
  return window['go']['main']['App']['ObtenerRutaProcesosData'](arg1, arg2);
}

export function OptimizarBD() {
  return window['go']['main']['App']['OptimizarBD']();
}

export function ReordenarRutaProcesosLeyenda(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReordenarRutaProcesosLeyenda'](arg1, arg2, arg3);
}

export function ReordenarRutaProcesosProceso(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReordenarRutaProcesosProceso'](arg1, arg2, arg3);
}

export function SetBackupMaxCopies(arg1) {
  return window['go']['main']['App']['SetBackupMaxCopies'](arg1);
}

export function ToggleBloquearRutaProcesosLeyenda(arg1) {
  return window['go']['main']['App']['ToggleBloquearRutaProcesosLeyenda'](arg1);
}
